apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argo-cd
spec:
  project: nginx
  source:
    repoURL: git@github.com
    path: nginx
    targetRevision: main
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - Validate=true
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    automated:
      prune: false
      selfHeal: false
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  ignoreDifferences:
    - group: apps
      kind: '*'
      jsonPointers:
        - /spec/replicas
