apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argo-cd
  annotations:
    argocd-image-updater.argoproj.io/image-list: nginx=docker.io/boatpand/mynginx:~1.0
    argocd-image-updater.argoproj.io/nginx.update-strategy: semver
    argocd-image-updater.argoproj.io/nginx.pull-secret: container-registry-secret
spec:
  project: nginx
  source:
    repoURL: git@github.com/boatpand/image-updater.git
    path: nginx
    targetRevision: main
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - Validate=true
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    automated:
      prune: false
      selfHeal: false

  destination:
    server: https://kubernetes.default.svc
    namespace: default
  ignoreDifferences:
    - group: apps
      kind: '*'
      jsonPointers:
        - /spec/replicas
